### ISSUE TITLE
Python is not installed as a framework

### ISSUE THREAD

**Issue by paulwilljones** [chaostoolkit/chaostoolkit-reporting#11]
When Python is installed using `brew` on Mac, Matplotlib will complain about Python not being installed as a framework during the reporting installation.
```
(venv) ~/repos/chaostoolkit-documentation-code (master) $ chaos report --help
Usage: chaos report [OPTIONS]

  Warning: entry point could not be loaded. Contact its author for help.

  Traceback (most recent call last):
    File "/Users/pauljones/repos/chaostoolkit-documentation-code/venv/lib/python3.6/site-packages/click_plugins/core.py", line 37, in decorator
      group.add_command(entry_point.load())
    File "/Users/pauljones/repos/chaostoolkit-documentation-code/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
      return self.resolve()
    File "/Users/pauljones/repos/chaostoolkit-documentation-code/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/Users/pauljones/repos/chaostoolkit-documentation-code/venv/lib/python3.6/site-packages/chaosreport/__init__.py", line 20, in <module>
      import matplotlib.pyplot as plt
    File "/Users/pauljones/repos/chaostoolkit-documentation-code/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
      _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    File "/Users/pauljones/repos/chaostoolkit-documentation-code/venv/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
      [backend_name], 0)
    File "/Users/pauljones/repos/chaostoolkit-documentation-code/venv/lib/python3.6/site-packages/matplotlib/backends/backend_macosx.py", line 17, in <module>
      from matplotlib.backends import _macosx
  RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either
reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.

Options:
  --help  Show this message and exit.
```

**Comment by paulwilljones** [comment]
https://stackoverflow.com/questions/21784641/installation-issue-with-matplotlib-python

`$ echo "backend: TkAgg" >> ~/.matplotlib/matplotlibrc`

**Comment by russmiles** [comment]
Sounds like we might be able to close this particular issue with some additional notes in the README? Or a separate FAQ document perhaps?

**Comment by Lawouach** [comment]
The readme would be the right place probably indeed :)

**Comment by paulwilljones** [comment]
Closing following #13
