### ISSUE TITLE
Reporting plugin not working when using 1.0.0rc1

### ISSUE THREAD

**Issue by AzMadu** [chaostoolkit/chaostoolkit-reporting#18]
docker run --user `id -u` -v `pwd`:/tmp/result -it chaostoolkit/reporting -- report --export-format=html5 journal.json journal2.json report.html
[2018-12-06 16:26:25 WARNING] 
    There is a new version (1.0.0rc1) of the chaostoolkit available.
    You may upgrade by typing:
    
    $ pip install -U chaostoolkit
    
    Please review changes at https://github.com/chaostoolkit/chaostoolkit/blob/master/CHANGELOG.md
    
Traceback (most recent call last):
  File "/usr/local/bin/chaos", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/chaosreport/cli.py", line 31, in report
    reports.append(generate_report(journal, export_format))
  File "/usr/local/lib/python3.6/site-packages/chaosreport/__init__.py", line 236, in generate_report
    template = get_report_template(journal["chaoslib-version"])
  File "/usr/local/lib/python3.6/site-packages/chaosreport/__init__.py", line 296, in get_report_template
    **vinfo._asdict()))):
  File "/usr/local/lib/python3.6/site-packages/semver.py", line 329, in match
    cmp_res = compare(version, match_version)
  File "/usr/local/lib/python3.6/site-packages/semver.py", line 282, in compare
    v1, v2 = parse(ver1), parse(ver2)
  File "/usr/local/lib/python3.6/site-packages/semver.py", line 65, in parse
    raise ValueError('%s is not valid SemVer string' % version)
ValueError: 1.0.0rc1 is not valid SemVer string

**Comment by AzMadu** [comment]
Inside my journal2.json file is the following:

"chaoslib-version": "1.0.0rc1"

**Comment by Lawouach** [comment]
Fixed in 0.12.0 actually but I forgot to upload the new docker image. It isn't built automatically for some reason I can't recall. I'll push it.

Then, if that works, please close this issue :)

**Comment by Lawouach** [comment]
Image 0.12.0 pushed https://hub.docker.com/r/chaostoolkit/reporting/tags/
