### ISSUE TITLE
Crash when trying to generate a report

### ISSUE THREAD

**Issue by joaoasrosa** [chaostoolkit/chaostoolkit-reporting#19]
**Issue**
When I try to run `chaos report` I got the following error:
```
Warning: entry point could not be loaded. Contact its author for help.


Traceback (most recent call last):
  File "/Users/joaorosa/.venvs/chaostk/lib/python3.7/site-packages/click_plugins/core.py", line 37, in decorator
    group.add_command(entry_point.load())
  File "/Users/joaorosa/.venvs/chaostk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Users/joaorosa/.venvs/chaostk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/joaorosa/.venvs/chaostk/lib/python3.7/site-packages/chaosreport/__init__.py", line 16, in <module>
    import cairosvg
  File "/Users/joaorosa/.venvs/chaostk/lib/python3.7/site-packages/cairosvg/__init__.py", line 42, in <module>
    from . import surface  # noqa isort:skip
  File "/Users/joaorosa/.venvs/chaostk/lib/python3.7/site-packages/cairosvg/surface.py", line 25, in <module>
    import cairocffi as cairo
  File "/Users/joaorosa/.venvs/chaostk/lib/python3.7/site-packages/cairocffi/__init__.py", line 50, in <module>
    ('libcairo.so', 'libcairo.2.dylib', 'libcairo-2.dll'))
  File "/Users/joaorosa/.venvs/chaostk/lib/python3.7/site-packages/cairocffi/__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so': dlopen(libcairo.so, 2): image not found
cannot load library 'libcairo.2.dylib': dlopen(libcairo.2.dylib, 2): image not found
cannot load library 'libcairo-2.dll': dlopen(libcairo-2.dll, 2): image not found
```
**Environment**
- Chaostoolkit
   - Version: `1.3.0`
- OS: macOs Catalina

**Comment by Lawouach** [comment]
Hi!

Reporting carries a lot of system dependencies unfortunately (damn pdf!), hence its plugin nature.

May I ask if you installed all the required dependencies?

**Comment by joaoasrosa** [comment]
This is a RTFM case. Shame on me. 
Closing the issue.

**Comment by girishbiw** [comment]
I am still getting the same error. How can this be fixed?

**Comment by Lawouach** [comment]
Can you confirm you installed the cairo libraries?
