### ISSUE TITLE
Can you document the list of package for installing it on RedHat 7?

### ISSUE THREAD

**Issue by sylock** [chaostoolkit/chaostoolkit-reporting#22]
Hello,

Tested on Red Hat 7.7. For PDF reports.

After some times searching and debugging, I found that when installing that list of software, the reporting in pdf is working:
    texlive-base
    texlive-latex-fonts
    texlive-latex-bin
    texlive-latex
    texlive-collection-fontsrecommended
    pandoc
    texlive-ec
    texlive-pdftex-bin
    texlive-pdftex-def

Maybe it would be a good idea to document it in the installation guide.:
https://docs.chaostoolkit.org/reference/usage/install/

**Comment by russmiles** [comment]
Probably best to document in an additional, platform-specific doc in this repo?

**Comment by ksraja00** [comment]
Hi Sylock,
I am facing issues while generating HTML report in RHEL8. Can you help me to resolve please.
I have installed the following packages but still getting error.

pip3 install pandoc
pip3 install pypandoc
pip3 install pypandoc-binary
pip3 install cairosvg
pip3 install chaostoolkit-lib
pip3 install click
pip3 install dateparser
pip3 install logzero
pip3 install jinja2
pip3 install matplotlib
pip3 install maya
pip3 install natural
pip3 install pygal
pip3 install semver



root@10-119-113-238:/apps/opt/addvol/dev/chaos # chaos report --export-format=html5 journal.json report.html
Traceback (most recent call last):
  File "/usr/local/bin/chaos", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/chaosreport/cli.py", line 36, in report
    reports.append(generate_report(journal, export_format))
  File "/usr/local/lib/python3.9/site-packages/chaosreport/__init__.py", line 270, in generate_report
    template = get_report_template(journal["chaoslib-version"])
  File "/usr/local/lib/python3.9/site-packages/chaosreport/__init__.py", line 368, in get_report_template
    "<={v}".format(v=semver.format_version(**vinfo._asdict())),
AttributeError: 'Version' object has no attribute '_asdict'
