### ISSUE TITLE
Reporting should not die on old experiment outputs

### ISSUE THREAD

**Issue by Lawouach** [chaostoolkit/chaostoolkit-reporting#4]
Since chaoslib 0.13.0, the reporting expects some new fields that didn't exist in the past. It should not die on that.

**Comment by russmiles** [comment]
Trace from seeing this:

chaos report --export-format=html5 chaos-report.json report.html
Traceback (most recent call last):
  File "/Users/russellmiles/.venvs/chaostk/bin/chaos", line 11, in <module>
    sys.exit(cli())
  File "/Users/russellmiles/.venvs/chaostk/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/russellmiles/.venvs/chaostk/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/russellmiles/.venvs/chaostk/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/russellmiles/.venvs/chaostk/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/russellmiles/.venvs/chaostk/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/russellmiles/.venvs/chaostk/lib/python3.6/site-packages/chaosreport/cli.py", line 20, in report
    generate_report(journal, report, export_format)
  File "/Users/russellmiles/.venvs/chaostk/lib/python3.6/site-packages/chaosreport/__init__.py", line 66, in generate_report
    report = template.render(journal)
  File "/Users/russellmiles/.venvs/chaostk/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/russellmiles/.venvs/chaostk/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/russellmiles/.venvs/chaostk/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/russellmiles/.venvs/chaostk/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/russellmiles/.venvs/chaostk/lib/python3.6/site-packages/chaosreport/template/index.md", line 41, in top-level template code
    The steady state was {%if steady_states.before.steady_state_met %} verified {% else %} not verified. {% endif %}
  File "/Users/russellmiles/.venvs/chaostk/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'steady_states' is undefined
