### ISSUE TITLE
Getting error while generating report in RHEL8 linux instances

### ISSUE THREAD

**Issue by ksraja00** [chaostoolkit/chaostoolkit-reporting#42]
Hello team,
Earlier we used CENTOS7 and the reporting feature worked well but for RHEL8 instances we are getting error. All the dependencies were installed. Please help to resolve.

root@10-119-113-238:/apps/opt/addvol/dev/chaos # chaos report --export-format=html5 journal.json report.html
Traceback (most recent call last):
  File "/usr/local/bin/chaos", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/chaosreport/cli.py", line 36, in report
    reports.append(generate_report(journal, export_format))
  File "/usr/local/lib/python3.9/site-packages/chaosreport/__init__.py", line 270, in generate_report
    template = get_report_template(journal["chaoslib-version"])
  File "/usr/local/lib/python3.9/site-packages/chaosreport/__init__.py", line 368, in get_report_template
    "<={v}".format(v=semver.format_version(**vinfo._asdict())),
AttributeError: 'Version' object has no attribute '_asdict'

**Comment by Lawouach** [comment]
This has been fixed in 0.14.3

**Comment by ksraja00** [comment]
Thanks @Lawouach
