### ISSUE TITLE
Crash while generating PDF report

### ISSUE THREAD

**Issue by nitinbhat** [chaostoolkit/chaostoolkit-reporting#47]
I see a crash while generating a report.

docker container run --volume $PWD:/tmp/result -it chaostoolkit/reporting -- report --export-format=pdf terminate-pod.json  report-2.pdf

Any workaround for this?

Traceback (most recent call last):
  File "/usr/local/bin/chaos", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/chaosreport/cli.py", line 37, in report
    save_report(header, reports, report_path, export_format)
  File "/usr/local/lib/python3.10/dist-packages/chaosreport/__init__.py", line 326, in save_report
    pypandoc.convert_file(
  File "/usr/local/lib/python3.10/dist-packages/pypandoc/__init__.py", line 168, in convert_file
    return _convert_input(discovered_source_files, format, 'path', to, extra_args=extra_args,
  File "/usr/local/lib/python3.10/dist-packages/pypandoc/__init__.py", line 426, in _convert_input
    raise RuntimeError(
RuntimeError: Pandoc died with exitcode "43" during conversion: Error producing PDF.
! Undefined control sequence.
l.196 /supervisord.pid\n

**Comment by cdsre** [comment]
We would probably need more details to be able to reproduce this. It looks like the `pandoc` binary its self died which is then propagated by through `pypandoc` and back to `ctk-reporting`.
